### PR TITLE
[WIP] Refactor MAGE integration

### PR DESCRIPTION
**Pull request by Koronen**
Refactors the MAGE integration by
- introducing a `Bookkeeper` factory
- introducing `Mage::Bookkeeper` and `Fake::Bookkeeper` implementing the interface of `.new(purchase)` and `#keep`
- adding a Rake task to export the current MAGE mappings
- removing MAGE-related columns from the database
- adding a controller and routes to update mappings on disk

Please note that this is still a work in progress! Some thing left to do include:
- [ ] make sure the mappings stay in memory most of the time, since they're not updated that often
- [ ] make sure the mappings are reloaded properly after updating them
- [ ] add authentication to the mappings controller
- [ ] add a link to `mage/mappings#index`
- [ ] remove references to MAGE from `db/seeds.rb`
- [ ]  align the columns in the mapping tables

### CODE REVIEW

**Comment by Koronen** [comment]
cashflow_mage_mappings

**Comment by Frost** [comment]
Tror du det går att snygga till kolumnerna i de där tabellerna? Nog för att det inte är min grej att klaga på riktigt, men det sticker lite i ögonen på mig...

**Comment by Koronen** [comment]
Det går nog. Jag skrev upp det på att göra-listan.

**Comment by bullfest** [comment]
</3

**Pull request closed without merging**
